config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root :to => 'welcome#index'
  get 'search', to: 'search#search'

  resources :welcome, only: [:index]
  resources :user_profile, only: [:new, :show, :edit, :update] do
    get 'friends', to: 'user_profile#friends'
    post 'follow_unfollow', to: 'user_profile#follow_unfollow'
    post 'friends/:friend_id/unfollow', to: 'user_profile#unfollow'
  end

  resources :posts, only: [:new, :create, :update, :destroy] do
    member do
      get :on_like_clicked
      post :add_comment
    end
  end

  resources :conversation, only: [:create, :index, :show] do
    resources :message, only: [:create]
  end
  
  # Devise
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/user_profile.rb
require 'elasticsearch/model'

class UserProfile < ApplicationRecord
  belongs_to :user

  has_many :posts, dependent: :destroy
  has_many :friendships, foreign_key: 'owner_id', dependent: :destroy
  has_many :friendships, foreign_key: 'follower_id', dependent: :destroy
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id', dependent: :destroy
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id', dependent: :destroy
  has_many :messages, foreign_key: 'author_id', dependent: :destroy

  has_one_attached  :avatar

  #================== Elasticsearch ==================
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  if Rails.env.development? || Rails.env.test?
    document_type "json"
  end


  ES_SETTING_TWO = {
      analysis: {
          index: {
              number_of_shards: 1,
              max_ngram_diff: 50
          },
          filter: {
              user_profile_nGram: {
                  type: 'ngram',
                  min_gram: 2,
                  max_gram: 3
              }
          },
          analyzer: {
              user_profile_analyzer: {
                  type: 'custom',
                  tokenizer: 'standard',
                  filter: [ 'lowercase', 'user_profile_nGram' ]
              }
          }
      }
  }

  settings ES_SETTING_TWO do
    mappings do
      indexes :name, type: 'text', analyzer: 'user_profile_analyzer'
    end
  end

  def update_es
    begin
      __elasticsearch__.update_document
    rescue Elasticsearch::Transport::Transport::Errors::NotFound => e
      __elasticsearch__.index_document
    end
  end

end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController

  # ======================== Filters ========================
  before_action :find_user_profile_by_params, only: [:show, :edit, :update, :follow_unfollow, :friends, :unfollow]

  # ======================== Display ========================

  def new

  end

  def show
    @posts = Post.all.where(user_profile_id: @profile)
  end

  # ======================== Edit ========================
  def edit
  end

  def update
    profile_data = params[:user_profile]
    @profile.update_attributes(:name => profile_data[:name], :age => profile_data[:age])

    if profile_data[:avatar].nil? == false
      @profile.avatar.attach(profile_data[:avatar])
      if @profile.avatar.image? == false
        @profile.avatar.purge
        flash[:alert] = "Please, select image"
        redirect_to action: 'edit'
        return
      end
    end

    if @profile.save
      redirect_to action: 'show'
    end
  end

  # ======================== Custom Actions ========================
  # Follow/Unfollow to/from params[:profile_id] user
  def follow_unfollow
    friendship = Friendship.where('owner_id = ? AND follower_id = ?', @profile.id, current_user.profile.id).first
    if friendship.present?
      friendship.destroy
    else
      friendship = Friendship.new
      friendship.update_attributes(owner_id: @profile.id, follower_id: current_user.profile.id)
      friendship.save
    end

    respond_to do |format|
      format.js
    end
  end

  # List of all friends
  def friends
    friendships = Friendship.where(follower_id: @profile.id)
    @friends = [ActiveRecord]
    friendships.each do |f|
      @friends.push(UserProfile.find(f.owner_id))
    end
    @friends.delete_at(0)
  end

  def unfollow
    friend_id = params[:friend_id]
    friendship = Friendship.where('owner_id = ? AND follower_id = ?', friend_id, @profile.id).first
    friendship.delete
    redirect_to user_profile_friends_path
  end

  # ======================== Private Methods ========================
  private

  def find_user_profile_by_params
    profile_id = params[:id] || params[:profile_id] || params[:user_profile_id]
    if is_id_number?(profile_id)
      @profile = UserProfile.find(profile_id)
    else
      @profile = User.where('link_hash = ?', profile_id).first.profile
    end
  end

end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/partials/user_profile/_user_info.html.haml
.d-flex.justify-content-between.align-items-center.px-2
  %span.profile-username= @profile.name
  = render partial: 'partials/user_profile/user_profile_action_buttons'
.d-flex.justify-content-between.profile-user-info-label-medium.px-2
  %span= "#{@profile.posts.count} posts"
  %span= "#{Friendship.where("owner_id = #{@profile.id}").count} followers"
  %span= "#{Friendship.where("follower_id = #{@profile.id}").count} following"

app/views/partials/user_profile/_user_profile_action_buttons.html.haml
#user-profile-action-buttons.d-flex.justify-content-end.align-items-center
  - if current_user.profile.id == params[:id].to_i
    = link_to 'Edit profile', edit_user_profile_path(@profile), method: :get, class: 'btn btn-light', id: 'edit-profile-button'
  - else
    - is_followed = Friendship.where('owner_id = ? AND follower_id = ?', @profile.id, current_user.profile.id).first.present?
    = link_to conversation_index_path(@profile), method: :post, class: 'bt-info-button', id: 'open-conversation-button', hidden: !is_followed do
      %i.fa.fa-envelope
    = link_to "#", method: :post, remote: true, class: "#{ is_followed ? "bt-secondary-button" : "bt-info-button"}", id: 'follow-unfollow-button', profile_id: @profile.id do
      %i{class: "#{is_followed ? "fa fa-user-minus" : "fa fa-user-plus"}"}