config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root :to => 'welcome#index'
  get 'search', to: 'search#search'

  resources :welcome, only: [:index]
  resources :user_profile, only: [:new, :show, :edit, :update] do
    get 'friends', to: 'user_profile#friends'
    post 'follow_unfollow', to: 'user_profile#follow_unfollow'
    post 'friends/:friend_id/unfollow', to: 'user_profile#unfollow'
  end

  resources :posts, only: [:new, :create, :update, :destroy] do
    member do
      get :on_like_clicked
      post :add_comment
    end
  end

  resources :conversation, only: [:create, :index, :show] do
    resources :message, only: [:create]
  end
  
  # Devise
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/user_profile.rb
require 'elasticsearch/model'

class UserProfile < ApplicationRecord
  belongs_to :user

  has_many :posts, dependent: :destroy
  has_many :friendships, foreign_key: 'owner_id', dependent: :destroy
  has_many :friendships, foreign_key: 'follower_id', dependent: :destroy
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id', dependent: :destroy
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id', dependent: :destroy
  has_many :messages, foreign_key: 'author_id', dependent: :destroy

  has_one_attached  :avatar

  #================== Elasticsearch ==================
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  if Rails.env.development? || Rails.env.test?
    document_type "json"
  end


  ES_SETTING_TWO = {
      analysis: {
          index: {
              number_of_shards: 1,
              max_ngram_diff: 50
          },
          filter: {
              user_profile_nGram: {
                  type: 'ngram',
                  min_gram: 2,
                  max_gram: 3
              }
          },
          analyzer: {
              user_profile_analyzer: {
                  type: 'custom',
                  tokenizer: 'standard',
                  filter: [ 'lowercase', 'user_profile_nGram' ]
              }
          }
      }
  }

  settings ES_SETTING_TWO do
    mappings do
      indexes :name, type: 'text', analyzer: 'user_profile_analyzer'
    end
  end

  def update_es
    begin
      __elasticsearch__.update_document
    rescue Elasticsearch::Transport::Transport::Errors::NotFound => e
      __elasticsearch__.index_document
    end
  end

end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController

  # ======================== Filters ========================
  before_action :find_user_profile_by_params, only: [:show, :edit, :update, :follow_unfollow, :friends, :unfollow]

  # ======================== Display ========================

  def new

  end

  def show
    @posts = Post.all.where(user_profile_id: @profile)
  end

  # ======================== Edit ========================
  def edit
  end

  def update
    profile_data = params[:user_profile]
    @profile.update_attributes(:name => profile_data[:name], :age => profile_data[:age])

    if profile_data[:avatar].nil? == false
      @profile.avatar.attach(profile_data[:avatar])
      if @profile.avatar.image? == false
        @profile.avatar.purge
        flash[:alert] = "Please, select image"
        redirect_to action: 'edit'
        return
      end
    end

    if @profile.save
      redirect_to action: 'show'
    end
  end

  # ======================== Custom Actions ========================
  # Follow/Unfollow to/from params[:profile_id] user
  def follow_unfollow
    friendship = Friendship.where('owner_id = ? AND follower_id = ?', @profile.id, current_user.profile.id).first
    if friendship.present?
      friendship.destroy
    else
      friendship = Friendship.new
      friendship.update_attributes(owner_id: @profile.id, follower_id: current_user.profile.id)
      friendship.save
    end

    respond_to do |format|
      format.js
    end
  end

  # List of all friends
  def friends
    friendships = Friendship.where(follower_id: @profile.id)
    @friends = [ActiveRecord]
    friendships.each do |f|
      @friends.push(UserProfile.find(f.owner_id))
    end
    @friends.delete_at(0)
  end

  def unfollow
    friend_id = params[:friend_id]
    friendship = Friendship.where('owner_id = ? AND follower_id = ?', friend_id, @profile.id).first
    friendship.delete
    redirect_to user_profile_friends_path
  end

  # ======================== Private Methods ========================
  private

  def find_user_profile_by_params
    profile_id = params[:id] || params[:profile_id] || params[:user_profile_id]
    if is_id_number?(profile_id)
      @profile = UserProfile.find(profile_id)
    else
      @profile = User.where('link_hash = ?', profile_id).first.profile
    end
  end

end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/user_profile/_user_posts_grid.html.haml
- post_number = 0
- @posts.each do |post|
  :javascript
    if ("#{post_number}" % 3 === 0) {
      $('.user-posts-grid-column').append(`
        <div class="row mt-2" id="post-photo-row-#{post_number / 3}"> </div>
      `);
    }
    $("#post-photo-row-#{post_number / 3}").append(`
      <div class="col-lg-4">
        <img src="#{url_for(post.photo)}" class="user-profile-post-image">
      </div>
    `);
    "#{post_number += 1}"

app/views/user_profile/edit.html.haml
= form_for @profile, url: user_profile_path do |f|
  .container.text-center.mt-5
    %h2.pt-5 Edit your profile
    .row
      .col-lg-4
      .col-lg-4
        .row.pt-2
          -#.col-lg-12
          = f.text_field :name, placeholder: 'Your name', class: 'form-control', value: @profile.name
        .row.pt-2
          -#.col-lg-12
          = f.text_field :age, placeholder: 'Your age', class: 'form-control', value: @profile.age
        .row.pt-2
          -#.col-lg-12
          .custom-file.text-left
            = f.file_field :avatar, id: :profile_avatar, accept: '.jpg, .png, .jpeg', class: 'custom-file-input', placeholder: 'Choose file', onchange: 'show_profile_avatar_preview(this);'
            = f.label 'Upload your profile pic', id: :profile_avatar_label, class: "custom-file-label", for: :profile_avatar
    .row.pt-3
      .col-lg-4
      .col-lg-4
        %img{:id => 'image_preview', :src => ""}
      .col-lg-4
    .row.pt-5
      .col-lg-12
        = f.submit 'Update', class: 'btn btn-outline-secondary'

app/views/user_profile/follow_unfollow.js.erb
$('#user-profile-action-buttons').replaceWith("<%= j render partial: 'partials/user_profile/user_profile_action_buttons' %>")

app/views/user_profile/friends.html.haml
.container
  .row
    .col-lg-4
    .col-lg-4.friends-list-column.px-0
      .d-flex.flex-row.align-items-center.px-0{style: "height: 50px; border-bottom: 1px solid rgb(219, 219, 219);"}
        .col-lg-12.px-0.text-center
          %span{class: "my-0 following-list-header"} Following
      .row
        .col-lg-12
          - @friends.each do |friend|
            .d-flex.flex-row.mt-3.px-2
              .col-lg-8.text-left.friend-short-info-column
                // Friend profile avatar
                - if friend.avatar.attached?
                  = image_tag friend.avatar, class: 'friends-list-avatar-photo'
                - else
                  = image_tag 'user_avatar_placeholder.png', class: 'friends-list-avatar-photo'
                // Name in profile link
                = link_to friend.name, user_profile_path(friend), class: 'link_to_profile'
              .col-lg-4.text-right.unfollow-button-div
                = link_to "friends/#{friend.id}/unfollow", method: :post, remote: true do
                  %button{class: "unfollow-button", id: "unfollow-button"} Unfollow
                -# = link_to user_profile_follow_unfollow_path(friend), method: :post, remote: true, profile_id: friend.id do
                -#   %button{class: "unfollow-button", id: "unfollow-button"} Unfollow
    .col-lg-4

app/views/user_profile/new.html.haml
.container
  .row
    .col-lg-12.text-center
      %h1 Sda

app/views/user_profile/show.html.haml
.container
  .row
    .col-lg-3
    -# User avatar
    .col-lg-2.text-center
      - if @profile.avatar.attached?
        = image_tag @profile.avatar, class: 'avatar-photo'
      - else
        = image_tag 'user_avatar_placeholder.png', class: 'avatar-photo'
    -# User info
    .col-lg-4.px-0
      = render partial: 'partials/user_profile/user_info'
    .col-lg-3
  .row.mt-5.mb-5.text-left
    .col-lg-1
    .col-lg-10.text-center
      - if current_user.profile.id == params[:id].to_i
        = button_to new_post_path(@profile), method: :get, class: 'btn btn-primary' do
          %span Create new post
          %i.fa.fa-plus
      - if @profile.posts.present?
        .dark-horizontal-separator.mt-3
        .row
          .col-lg-12
            %span{:style => "font-size: 30px; color: #138496;"}= "#{@profile.name} posts".upcase

            -# Displays users posts
            .row.pt-5
              .col-lg-12.user-posts-grid-column
                = render partial: 'user_posts_grid'
    .col-lg-1